### ISSUE TITLE
have bubblebath, will travel

### ISSUE THREAD

**Issue by esaruoho** [antonhornquist/jon-pd#2]
Hi, great patch!
Now, how would I use the name bubblebath to send information to jon~ so that it'd have this specific type of reverb? I'm trying to incorporate it into my pd-based ambient drone setup, and this would definitely replace both the original dattorro.pd and the rtap/gothom~ (which is unfortunately an external, and only available for intel laptops so not ARM architecture).

<img width="751" alt="Screenshot 2023-03-19 at 11 52 12" src="https://user-images.githubusercontent.com/4966687/226167155-31f15642-b99b-4483-9c35-d6c1b5492bfc.png">

i tried just copypasting the bubblebath settings and sending them to the third output, but it doesn't seem to work.
what should i do?

also, is it recommended to just use one instance of jon~? i'm seeing the parameters + slider stuff don't include `$0-` at the start, differentiating their functionality.

**Comment by esaruoho** [comment]
ok, after i modified param1, param2, param3, param4, param5, param6, param7, param8, param9 to be
predelay, bandwidth, damping, decay, input_diffusion1, input_diffusion2, decay_diffusion1, decay_diffusion2, excursion.
the message still did nothing.
so i ended up doing this:
<img width="649" alt="Screenshot 2023-03-19 at 23 18 43" src="https://user-images.githubusercontent.com/4966687/226210295-a3eafa1d-7082-4995-9e35-1919011795dd.png">

what's the right method of doing this, @antonhornquist ? i'd prefer to not have so many cluttered messages just to get a specific type of reverb..

**Comment by antonhornquist** [comment]
The reason you can't get this to work with the message box containing "param1", "param2", ... in the first place is that the presets in the help file assumes the "params" (which is the graphical representation of the reverb parameters) and "receive_params" subpatches are in the patch. The "params" subpatch define receive symbols used in the message box (param1, param2, et cetera...) in its UI components and forwards these messages to new receive symbols (predelay, damping, ...) which, in turn, are defined in the "receive_params" subpatch. This subpatch then routes these messages to what messages the reverb abstraction expects to the reverb abstraction's right-most outlet. This is the only way to set the parameters in the jon.pd patch (as you later found). I've tried to depict the flow with some screenshots.

Note that in Pd, message boxes may contain multiple messages. Any message that follows a semicolon must specify a symbol (in the help file "param1", "param2", and so on) to which the message will be sent. See http://msp.ucsd.edu/Pd_documentation/x2.htm#s3.4.

So without the "params" and "receive_params" subpatches messages sent to receive symbols in these subpatches will not be routed correctly to the reverb.

What you showed in your second comment works well. If wanted, an alternative would be to copy over the "receive_params" subpatch to your patch and use the receive symbols (predelay, et cetera) in that subpatch to make a message box similar to the first one you showed (the one with all the params), but to use the predelay, bandwith, et cetera receive symbols instead. Note though, that these symbols are defined globally so they might clash with other similarly named symbols in use. The safest way is probably to do what you showed in your second comment.

![image](https://user-images.githubusercontent.com/32165/226892021-dc0b7a0f-7808-4c6e-a1da-3b0d2b8a8662.png)

![image](https://user-images.githubusercontent.com/32165/226892094-ac2de755-06d2-490f-9683-d66fca708029.png)

![image](https://user-images.githubusercontent.com/32165/226892203-e8b1deaa-5ad8-441e-846a-27c9717f956d.png)

![image](https://user-images.githubusercontent.com/32165/226892301-7820a561-21df-42fa-b8d9-ad9a79b67b5a.png)

![image](https://user-images.githubusercontent.com/32165/226892391-c5685bae-7066-48aa-8638-1c57180071ff.png)
